name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function to build and push
        uses: dagger/dagger-for-github@8.0.0
        with:
          call: --source . build publish --token env:GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
