name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function to release
        uses: dagger/dagger-for-github@8.0.0
        with:
          call: --source . release --github-token env:GITHUB_TOKEN --ci=true --dry-run=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
